"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { ArrowLeft, Bookmark, LoaderCircle, Copy, Check } from "lucide-react";
import { getAgencySavedContent } from "@/services/agency-tools.api";

export default function AgencySavedContentPage() {
  const [savedItems, setSavedItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [copiedId, setCopiedId] = useState(null);

  useEffect(() => {
    const fetchContent = async () => {
      try {
        setLoading(true);
        const res = await getAgencySavedContent();
        setSavedItems(res.data || []);
      } catch (err) {
        setError(err.message || "Failed to load saved content");
      } finally {
        setLoading(false);
      }
    };
    fetchContent();
  }, []);

  const handleCopy = async (id, content) => {
    try {
      await navigator.clipboard.writeText(content);
      setCopiedId(id);
      setTimeout(() => setCopiedId(null), 2000);
    } catch {
      // Ignore copy error
    }
  };

  if (loading) {
    return (
      <main className="flex min-h-screen items-center justify-center bg-gradient-to-b from-violet-50 via-white to-white text-zinc-900">
        <div className="flex items-center gap-3 text-violet-700">
          <LoaderCircle size={24} className="animate-spin" />
          <span className="font-medium">Loading content...</span>
        </div>
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-white font-sans text-zinc-900">
      <div className="pointer-events-none absolute left-1/2 top-0 h-96 w-[800px] max-w-full -translate-x-1/2 rounded-full bg-violet-300/20 blur-3xl" />

      <div className="relative z-10 mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
        <header className="mb-8 flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <Link href="/agency/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-violet-700 hover:text-violet-800 mb-2">
              <ArrowLeft size={16} /> Back to Dashboard
            </Link>
            <h1 className="mt-2 text-3xl font-black leading-tight tracking-tight text-zinc-950">
              Recent Client Content
            </h1>
            <p className="mt-2 text-sm leading-relaxed text-zinc-600">
              Browse all AI content generated by your agency.
            </p>
          </div>
        </header>

        {error && (
          <div className="mb-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">
            {error}
          </div>
        )}

        <div className="grid gap-6 lg:grid-cols-2">
          {savedItems.length === 0 ? (
            <div className="col-span-full rounded-3xl border border-zinc-200 bg-white p-16 text-center shadow-sm">
              <Bookmark size={48} className="mx-auto mb-4 text-violet-200" />
              <h3 className="text-xl font-bold text-zinc-900">No content saved</h3>
              <p className="mt-2 text-zinc-500">Generate content using the AI tools to see them here.</p>
            </div>
          ) : (
            savedItems.map((item) => (
              <div key={item._id} className="rounded-3xl border border-zinc-200 bg-white p-6 shadow-sm transition hover:shadow-md hover:border-violet-200 flex flex-col h-full">
                <div className="flex items-start justify-between gap-4 mb-4">
                  <div>
                    <h3 className="font-bold text-zinc-900 line-clamp-1" title={item.title}>{item.title}</h3>
                    <span className="inline-block mt-2 rounded-full bg-violet-100 px-3 py-1 text-xs font-semibold capitalize text-violet-700">
                      {item.type.replaceAll("-", " ")}
                    </span>
                  </div>
                  <button
                    onClick={() => handleCopy(item._id, item.content)}
                    className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-zinc-200 bg-zinc-50 text-zinc-500 hover:bg-violet-50 hover:text-violet-700 transition"
                    title="Copy to clipboard"
                  >
                    {copiedId === item._id ? <Check size={18} className="text-emerald-600" /> : <Copy size={18} />}
                  </button>
                </div>
                
                <div className="rounded-2xl bg-zinc-50 p-4 text-sm text-zinc-700 font-mono whitespace-pre-wrap border border-zinc-100 flex-1 overflow-y-auto max-h-48">
                  {item.content}
                </div>
                
                <p className="mt-4 text-xs text-zinc-400">
                  Created {new Date(item.createdAt).toLocaleDateString()}
                </p>
              </div>
            ))
          )}
        </div>
      </div>
    </main>
  );
}
